### ISSUE TITLE
Allow root dataset to have more than one type

### ISSUE THREAD

**Issue by moisbo** [ResearchObject/ro-crate-py#125]
Fails if root dataset has an array as a value for @type 

eg. @type = ['Dataset', 'RepositoryCollection']

Note: @ptsefton says: Can we always code defensively, please.

https://github.com/ResearchObject/ro-crate-py/blob/9c010654dce2b8cd9ca4e99dd73885439885e4fc/rocrate/rocrate.py#L154

**Comment by simleo** [comment]
Defensive coding does not mean ignoring the spec. Enforcing restrictions often makes the implementation less verbose and more efficient. In this case, it allows to perform an _O_(1) check rather than a _O_(_n_) one. For type lists, however, this should not be a big deal (hopefully nobody's going to use thousands of types for any entity), so we can make this change in the library before it makes it into the spec (see https://github.com/ResearchObject/ro-crate/issues/182).
